"""init

Revision ID: 696f2bdbe4fa
Revises: 
Create Date: 2023-03-23 22:16:24.027807

"""
import sqlalchemy as sa
from alembic import op

import utils

# revision identifiers, used by Alembic.
revision = '696f2bdbe4fa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session',
                    sa.Column('id', utils.mysql_uuid.BinaryUUID(length=16),
                              nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('id')
                    )
    type_table = op.create_table('type',
                                 sa.Column('name', sa.String(length=100),
                                           nullable=False),
                                 sa.Column('id', sa.Integer(),
                                           autoincrement=True,
                                           nullable=False),
                                 sa.PrimaryKeyConstraint('id'),
                                 sa.UniqueConstraint('name')
                                 )
    op.create_index(op.f('ix_type_id'), 'type', ['id'], unique=False)
    op.create_table('package',
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('weight', sa.Float(), nullable=False),
                    sa.Column('type_id', sa.Integer(), nullable=True),
                    sa.Column('usd_price', sa.Float(), nullable=False),
                    sa.Column('cost', sa.Float(), nullable=True),
                    sa.Column('session_id',
                              utils.mysql_uuid.BinaryUUID(length=16),
                              nullable=True),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('id', sa.Integer(), autoincrement=True,
                              nullable=False),
                    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
                    sa.ForeignKeyConstraint(['type_id'], ['type.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_package_id'), 'package', ['id'], unique=False)
    # ### end Alembic commands ###
    op.execute('ALTER TABLE package MODIFY '
               'updated_at DATETIME NOT NULL DEFAULT NOW() ON UPDATE NOW()')
    data = [
        {'name': 'electronic'},
        {'name': 'wear'},
        {'name': 'other'},
    ]

    # insert data to table type
    op.bulk_insert(type_table, data)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_package_id'), table_name='package')
    op.drop_table('package')
    op.drop_index(op.f('ix_type_id'), table_name='type')
    op.drop_table('type')
    op.drop_table('session')
    # ### end Alembic commands ###
